contributors.txt
=> Git and GitHub Labs

contributors.txt
Added Taylor Finelli and email to contributors.txt
=> Added Taylor Finelli and email to contributors.txt

contributors.txt
Added Name (Stefano Rubini) and Email (rubini@unlv.nevada.edu) to contributors.txt.
=> contributors.txt modifications

contributors.txt
Add Marcos's info to contributors.txt and fix formatting inconsistency in line 6.
=> Add Marcos Villanueva Abreu to contributors along with email and fix file formatting

contributors.txt
Added my info to the contributors.txt file
=> Added Name to Contributors

contributors.txt
=> Daniel's commit (Part 1)

code_snippets/elliot_complex_code.py
add elliot's complex code snippet. Closes #41
=> Elliot's complex code snippet

code_snippets/elliot_documentation.sh
add elliot_documentation.sh (code that needs to be documented for lab 4 task 2.2). Closes #39
=> Add documentation to complex command

.gitignore, code_snippets/elliot_cbright.c, documentation/bspeww.sh
create code_snippets folder and elliot_cbright.c without refactors. closes #37
=> add elliot's code snippet for ChatGPT lab

code_snippets/thien_calculator.py
Resolve #43 
Based on the refactor of gpt:
Here is the [link](https://chat.openai.com/share/3ec83cdc-5939-420e-bccc-ab4266462516) to the conversation.
=> 🏯feat: refactor code for task 2.1 CHAT GPT Lab

code_snippets/thien_documentation.tsx
=> 🗓 feat: refactor to aye aye, task 2.2 CHAT GPT Lab

repo_mining/Taylor_scatterplot.py
Overrode the original file instead of creating a separate file. Reverted old file and added the new, ChatGPT-updated one to code_snippets directory.
=> Move updated Taylor_scatterplot.py file to code_snippets

code_snippets/Taylor_scatterplot.py
I didn't properly add files from previous commit. I'm still new to this soz
=> Add new ChatGPT-refactored file

code_snippets/Taylor_HighlightBackground.tsx
I utilized ChatGPT to solve issue #64.
I pasted the issue and corresponding code segment into ChatGPT and it generated a response with an updated, clarified code segment. It put comments every few lines to describe what was happening and why.
The original question (what does the setTimeout function do?) has been answered in the comments of the code: it runs the function after a certain specified delay. 
ChatGPT also explained another thing to me that I did not think to ask: why does it remove an event listener? It is to serve as a cleanup function when the component unmounts. 
Relevant ChatGPT conversation: https://chat.openai.com/share/0f5cf9fb-6924-4586-81fd-d4a16d814e21
=> Closes #64: ChatGPT generated comments for clarity on Taylor_HighlightBackground.tsx

code_snippets/Taylor_HighlightBackground.tsx
I utilized ChatGPT to solve issue #64.
I pasted the issue and corresponding code segment into ChatGPT and it generated a response with an updated, clarified code segment. It put comments every few lines to describe what was happening and why.
The original question (what does the setTimeout function do?) has been answered in the comments of the code: it runs the function after a certain specified delay. 
ChatGPT also explained another thing to me that I did not think to ask: why does it remove an event listener? It is to serve as a cleanup function when the component unmounts. 
Relevant ChatGPT conversation: https://chat.openai.com/share/0f5cf9fb-6924-4586-81fd-d4a16d814e21
=> 64 understanding complex code taylors personal website highlightbackground file

code_snippets/thomas_dataStructMain.cpp
=> Thomas refactor

code_snippets/genAI.py, code_snippets/thomas_dataStructMain.cpp
added documentation from ChatGPT ¯\_( ͡° ͜ʖ ͡°)_/¯
=> Thomas Task 2.2

code_snippets/Marcos_Timer.tsx
Closes #71 
This Timer component contains code that is hard to read and understand for outside developers. It lacks documentation and proper formatting for the time. Additionally, it lacks the ability to reset the timer.
=> Add Timer component to be refactored in Task 2.1 of ChatGPT lab

code_snippets/Marcos_useOutsideClickDetector.tsx
=> File to add documentation for task 2.2 of ChatGPT lab

code_snippets/Marcos_complex_code.ts
Close #75 
ChatGPT gave really good recommendation in terms of improving the code to make it more readable and understandable. Separating the animeSort function into smaller and modular functions helps in understanding what the code is doing. Additionally, instead of using nested setTimouts its better to use Promises which could improve the performance and helps reduce the complexity of the code. 
ChatGPT Link: https://chat.openai.com/share/ec13eeb2-c9e1-44f3-910b-81e3a4f58599
=> Add complex code for task 2.3 of ChatGpt lab

code_snippets/Miguel_date.cpp
Closes #81 
Added ChatGPT code for Task 2.1: Code refactoring on Miguel_date.cpp to make the date functions more concise.
Link to ChatGPT conversation should be here: https://chat.openai.com/share/c05aa964-d63c-455c-a1ba-37486cc28520
=> Cleaner and more concicse code for Miguel_date.cpp from ChatGPT.

code_snippets/Stefano_complexCode.cpp
This commit includes a link to a ChatGPT conversation where I asked it to explain a code snippet that I was confused on by providing comments to every line of the code snippet, which helps to distinguish the code snippet from the rest of the code as there are no other comments, other than the ones provided by ChatGPT. The code snippet in question can be found in the issue that is linked at the bottom of this commit. The conversation with ChatGPT documents how the code snippet worked in relation to the rest of the provided code body, which helped to bridge the gap between the code snippet and how much I understand it. Furthermore, ChatGPT was able to provide me with refactored code for the code snippet to serve as insight after regaining understanding of my code; I can now improve upon the …
=> Added Stefano_complexCode.cpp

code_snippets/daniel_ticTacToe.cpp
Closes #84 
According to chatGPT, the changes made are
1. Used constants BOARD_SIZE and BOARD_CELLS instead of magic numbers.
2. Renamed the players struct to Player with capitalized names.
3.Renamed variables to be more descriptive (isInputValid, isCellAvailable).
4.Encapsulated input validation and cell availability checks into separate functions.
5.Improved error handling using exception handling.
6.Made the selectCell function more modular by separating user input handling from game logic.
7.Used cout for output and removed unnecessary debug output.
8.Structured the code with appropriate indentation and spacing for readability.
These changes were made in order to fix some of the duplication issues, as well as the overly nested code.
=> Task 2.1: Code Refactoring - Daniel

code_snippets/Miguel_fib.cpp
Closes #88 
Added and updated Miguel_fib.cpp in code_snippets to include meaningful documentation from ChatGPT regarding the mathematical process of squaring a matrix, as well as how it was handled in the implementation itself.
ChatGPT essentially helped add comments to visually illustrate how squaring a matrix would work in theory, and then added comments throughout the function showcasing what was going on step-by-step while referring to the theoretical discussion before the function itself.
Link to ChatGPT conversation: https://chat.openai.com/share/127078f3-fc60-415c-8c2e-4b583c36f695
=> Adding documentation to Miguel_fib.cpp

code_snippets/Miguel_astar.py
Closes #90 
Added a python A* program and ran it through ChatGPT to better understand it while also adding a recommendation + notes regarding a different heuristic function, as well as when one might want to use it instead. Didn't implement different data structures to utilize the new heuristic algorithm, but one can modify the original A* algorithm to be compatible with it (very likely through the use of ChatGPT as well).
Link to ChatGPT conversation: https://chat.openai.com/share/4756a0b6-f1ef-4a06-b377-1aa2bb3546e8
=> A* Algorithm + Recommendation from ChatGPT on heuristic function

code_snippets/daniel_ticTacToe.cpp
=> Task 2.1 Done

code_snippets/daniel_documentation.cpp
Closes #95 
I added documentation to my code that answers project Euler's first problem (Multiples of 3 and 5, https://projecteuler.net/problem=1). The comments were gotten from a prompt given to ChatGPT. I also had it explain the math and added comments myself in accordance with the explanation given to me.
=> 95 task 22 documentation assistance daniel

code_snippets/daniel_pythag_complex.cpp
Closes #99 
I got clarification on the program. This program works by using three formulas 
a = m^2 - n^2
b = 2 * m * n
c = m^2 + n^2, where m and n are two positive integers where m < n, and the integers a, b, and c are those from the Pythagorean theorem.
ChatGPT also helped me refactor the code to become more readable. Functionality was added to check if the integers a,b, and c, found from the combinations of m and n, are Pythagorean triplets and also to find the Pythagorean product.
ChatGPT link:  https://chat.openai.com/share/4a985cdf-7830-4c82-9377-fa17040262ce
=> Task 2.3: Understanding Complex Code

code_snippets/Yidong_PrimeNum.cpp
This PR contains the code snippet in issue #100.
=> Task 2.1: Code Refactoring - Yidong
